name: 'submodule updates'

on: 
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'pwqbot/rumble'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'pwqbot'
    steps:
    - uses: actions/checkout@v3
    - name: run action
      id: run_action
      uses: ./
      with: 
        github_token: ${{ secrets.RELEASE_HUB_SECRET }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
        owner: ${{ env.OWNER }}
